apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bdzqw0y2o-java-quarkus
  janus-idp.io/tekton: bdzqw0y2o-java-quarkus
  backstage.io/kubernetes-id: bdzqw0y2o-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bdzqw0y2o-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
